version: 2
mergeable:
  - when: pull_request.opened
    name: "Greet a contributor"
    validate: []
    pass:
      - do: comment
        payload:
          body: >
            Thanks for your contribution!  Unfortunately, we don't use GitHub pull requests to manage code contributions to DPS8M.  Please visit the [GitLab repository](https://gitlab.com/dps8m/dps8m) to contribute to this project.
      - do: close
