############################################################################
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered "AS-IS",
# without any warranty.
############################################################################
# GitLab CI/CD Configuraton
############################################################################

.scriptCommon: &scriptCommon |
    # scriptCommon
    echo "Project Name              : $CI_PROJECT_TITLE"
    echo "Project Git Commit        : $CI_COMMIT_SHA"
    echo "Project Git Branch        : $CI_COMMIT_BRANCH"
    echo "GitLab CI User Details    : $GITLAB_USER_LOGIN - $GITLAB_USER_NAME ($GITLAB_USER_ID) $GITLAB_USER_EMAIL"
    echo "GitLab CI Job Name        : $CI_JOB_NAME"
    echo "GitLab CI Job ID          : $CI_JOB_ID"
    echo "GitLab CI Job Stage       : $CI_JOB_STAGE"
    echo "GitLab CI Runner Details  : $CI_RUNNER_VERSION ($CI_RUNNER_REVISION)"

############################################################################

.scriptBuildlibuvCLANG: &scriptBuildlibuvCLANG |
    # scriptBuildlibuvCLANG
    wget -nv https://github.com/libuv/libuv/archive/v1.x.zip
    unzip -xa v1.x.zip && cd libuv-1.x && sh ./autogen.sh
    CC=clang ./configure --disable-shared --enable-static
    make && make install && cd ..

############################################################################

.scriptBuildlibuvGCC: &scriptBuildlibuvGCC |
    # scriptBuildlibuvGCC
    wget -nv https://github.com/libuv/libuv/archive/v1.x.zip
    unzip -xa v1.x.zip && cd libuv-1.x && sh ./autogen.sh
    CC=gcc ./configure --disable-shared --enable-static
    make && make install && cd ..

############################################################################

.scriptBuildlibuvMGW64: &scriptBuildlibuvMGW64 |
    # scriptBuildlibuvMGW64
    wget -nv https://github.com/libuv/libuv/archive/v1.x.zip
    unzip -xa v1.x.zip && cd libuv-1.x && sh ./autogen.sh
    ./configure --disable-shared --enable-static --host=x86_64-w64-mingw32
    make && make install && cd ..

############################################################################

image: silkeh/clang

############################################################################

default:
  before_script:
    - uname -a 2> /dev/null || true > /dev/null 2>&1
    - apt-get update -y -qq || true > /dev/null 2>&1
    - apt-get install -y -qq mingw-w64 gcc libtool unzip autoconf-archive timelimit
    - clang --version 2> /dev/null || true > /dev/null 2>&1
    - gcc --version 2> /dev/null ||  true > /dev/null 2>&1
    - cc --version 2> /dev/null || true > /dev/null 2>&1
    - lsb_release -d 2> /dev/null || true > /dev/null 2>&1
    - cat /etc/*elease 2> /dev/null || true > /dev/null 2>&1
    - echo "The DPS8M Development Team - CI/CD Test Build ${CI_JOB_ID:-}" 2> /dev/null | tee .builder.txt 2> /dev/null || true > /dev/null 2>&1

############################################################################

stages:
  - build_linuxclang
  - build_linuxclang_nolockless
  - build_linuxgcc
  - build_linuxgcc_nolockless
  - build_mingw64
  - build_mingw64_nolockless
  - build_sourcekit

############################################################################

build linuxclang:
  stage: build_linuxclang
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuvCLANG
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra -fdata-sections -ffunction-sections -Wshadow -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wundef -Wconversion -Weverything"; make CC=clang LIBUV="/usr/local/lib/libuv.a -lpthread" LDFLAGS="-Wl,--gc-sections -Wl,--print-gc-sections" W=1 V=1 -j 3 --output-sync --print-directory -k; exit "${?}"'
    - sh -x -c 'printf %s\\n "show version" | timelimit -T 10 "./src/dps8/dps8" ; exit "${?}"'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf
      - /builds/dps8m/dps8m/src/punutil/punutil
      - /builds/dps8m/dps8m/src/dps8/useddef.txt

############################################################################

build linuxgcc:
  stage: build_linuxgcc
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuvGCC
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra -fdata-sections -ffunction-sections -Wshadow -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wundef -Wconversion"; make CC=gcc LIBUV="/usr/local/lib/libuv.a -lpthread" LDFLAGS="-Wl,--gc-sections -Wl,--print-gc-sections" W=1 V=1 -j 3 --output-sync --print-directory -k; exit "${?}"'
    - sh -x -c 'printf %s\\n "show version" | timelimit -T 10 "./src/dps8/dps8" ; exit "${?}"'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf
      - /builds/dps8m/dps8m/src/punutil/punutil
      - /builds/dps8m/dps8m/src/dps8/useddef.txt

############################################################################

build linuxclang_nolockless:
  stage: build_linuxclang_nolockless
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuvCLANG
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra -fdata-sections -ffunction-sections -Wshadow -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wundef -Wconversion -Weverything"; make CC=clang LIBUV="/usr/local/lib/libuv.a -lpthread" NO_LOCKLESS=1 LDFLAGS="-Wl,--gc-sections -Wl,--print-gc-sections" W=1 V=1 -j 3 --output-sync --print-directory -k; exit "${?}"'
    - sh -x -c 'printf %s\\n "show version" | timelimit -T 10 "./src/dps8/dps8" ; exit "${?}"'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf
      - /builds/dps8m/dps8m/src/punutil/punutil
      - /builds/dps8m/dps8m/src/dps8/useddef.txt

############################################################################

build linuxgcc_nolockless:
  stage: build_linuxgcc_nolockless
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuvGCC
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra -fdata-sections -ffunction-sections -Wshadow -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wundef -Wconversion"; make CC=gcc LIBUV="/usr/local/lib/libuv.a -lpthread" NO_LOCKLESS=1 LDFLAGS="-Wl,--gc-sections -Wl,--print-gc-sections" W=1 V=1 -j 3 --output-sync --print-directory -k; exit "${?}"'
    - sh -x -c 'printf %s\\n "show version" | timelimit -T 10 "./src/dps8/dps8" ; exit "${?}"'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf
      - /builds/dps8m/dps8m/src/punutil/punutil
      - /builds/dps8m/dps8m/src/dps8/useddef.txt

############################################################################

build mingw64:
  stage: build_mingw64
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuvMGW64
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra -fdata-sections -ffunction-sections -Wshadow -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wundef -Wconversion"; make CC="x86_64-w64-mingw32-gcc -I/usr/local/include -L/usr/local/lib -pthread" CROSS="MINGW64" LIBUV="/usr/local/lib/libuv.a -lpthread" LDFLAGS="-Wl,--gc-sections -Wl,--print-gc-sections" W=1 V=1 -j 3 --output-sync --print-directory -k; exit "${?}"'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8.exe
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf.exe
      - /builds/dps8m/dps8m/src/punutil/punutil.exe
      - /builds/dps8m/dps8m/src/dps8/useddef.txt

############################################################################

build mingw64_nolockless:
  stage: build_mingw64_nolockless
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuvMGW64
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra -fdata-sections -ffunction-sections -Wshadow -Wdouble-promotion -Wformat=2 -Wformat-truncation -Wundef -Wconversion"; make CC="x86_64-w64-mingw32-gcc -I/usr/local/include -L/usr/local/lib -pthread" CROSS="MINGW64" LIBUV="/usr/local/lib/libuv.a -lpthread" LDFLAGS="-Wl,--gc-sections -Wl,--print-gc-sections" W=1 V=1 NO_LOCKLESS=1 -j 3 --output-sync --print-directory -k; exit "${?}"'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8.exe
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf.exe
      - /builds/dps8m/dps8m/src/punutil/punutil.exe
      - /builds/dps8m/dps8m/src/dps8/useddef.txt

############################################################################

build sourcekit:
  stage: build_sourcekit
  only:
    - master
  script:
    - *scriptCommon
    - sh -x -c 'make reallyclean V=1 -j 3 --output-sync --print-directory -k; exit "${?}"'
    - sh -x -c 'make dist V=1 -j 3 --output-sync --print-directory -k; exit "${?}"'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/sources.tar.gz

############################################################################
