############################################################################

.scriptCommon: &scriptCommon |
    # scriptCommon
    echo "Project Name              : $CI_PROJECT_TITLE"
    echo "Project Git Commit        : $CI_COMMIT_SHA"
    echo "Project Git Branch        : $CI_COMMIT_BRANCH"
    echo "GitLab CI User Details    : $GITLAB_USER_LOGIN - $GITLAB_USER_NAME ($GITLAB_USER_ID) $GITLAB_USER_EMAIL"
    echo "GitLab CI Job Name        : $CI_JOB_NAME"
    echo "GitLab CI Job ID          : $CI_JOB_ID"
    echo "GitLab CI Job Stage       : $CI_JOB_STAGE"
    echo "GitLab CI Runner Details  : $CI_RUNNER_VERSION ($CI_RUNNER_REVISION)"

############################################################################

.scriptBuildlibuv: &scriptBuildlibuv |
    # scriptBuildlibuv
    wget -S https://github.com/libuv/libuv/archive/v1.x.zip
    unzip -xa v1.x.zip && cd libuv-1.x && sh ./autogen.sh
    ./configure --disable-shared --enable-static
    make V=1 && make V=1 install && cd ..

############################################################################

.scriptBuildlibuvMGW64: &scriptBuildlibuvMGW64 |
    # scriptBuildlibuvMGW64
    wget -S https://github.com/libuv/libuv/archive/v1.x.zip
    unzip -xa v1.x.zip && cd libuv-1.x && sh ./autogen.sh
    ./configure --disable-shared --enable-static --host=x86_64-w64-mingw32
    make V=1 && make V=1 install && cd ..

############################################################################

image: silkeh/clang

############################################################################

default:
  before_script:
    - uname -a 2> /dev/null || true > /dev/null 2>&1
    - apt-get update -y -qq || true > /dev/null 2>&1
    - apt-get install -y -qq mingw-w64 libtool unzip autoconf-archive
    - clang --version 2> /dev/null || true > /dev/null 2>&1
    - gcc --version 2> /dev/null ||  true > /dev/null 2>&1
    - cc --version 2> /dev/null || true > /dev/null 2>&1
    - lsb_release -d 2> /dev/null || true > /dev/null 2>&1

############################################################################

stages:
  - build_linux
  - build_linux_lockless
  - build_mingw64

############################################################################

build linux:
  stage: build_linux
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuv
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra"; make LIBUV="/usr/local/lib/libuv.a -lpthread" W=1 V=1'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf

############################################################################

build linux_lockless:
  stage: build_linux_lockless
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuv
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra"; make LIBUV="/usr/local/lib/libuv.a -lpthread" LOCKLESS=1 W=1 V=1'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf

############################################################################

build mingw64:
  stage: build_mingw64
  only:
    - master
  script:
    - *scriptCommon
    - *scriptBuildlibuvMGW64
    - sh -x -c 'export CFLAGS="${CFLAGS:-} -Wall -Wextra"; make CC="x86_64-w64-mingw32-gcc -I/usr/local/include -L/usr/local/lib -pthread" CROSS="MINGW64" LIBUV="/usr/local/lib/libuv.a -lpthread" W=1 V=1'
  dependencies: []
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8.exe
      - /builds/dps8m/dps8m/src/prt2pdf/prt2pdf.exe

############################################################################
