# SPDX-License-Identifier: MIT-0
# scspell-id: 9bcd83de-4bed-11ef-8000-922037bebb33
# Copyright (c) 2024-2025 The DPS8M Development Team

version = 1
SPDX-PackageName = "DPS8M"
SPDX-PackageSupplier = "The DPS8M Development Team <contact-project+dps8m-dps8m-10664906-issue-@incoming.gitlab.com>"
SPDX-PackageDownloadLocation = "https://gitlab.com/dps8m/dps8m"

[[annotations]]
path = ["docs/hpages/archetypes/**", "docs/hpages/data/**", "docs/hpages/layouts/**", "docs/hpages/themes/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 Robert Kaussow <mail@thegeeklab.de>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/libsir/**"
precedence = "aggregate"
SPDX-FileCopyrightText = ["2018-2024 Ryan M. Lederman <lederman@gmail.com>", "2018-2024 Jeffrey H. Johnson <trnsz@pobox.com>"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "src/libbacktrace/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2012-2016 Free Software Foundation, Inc."
SPDX-License-Identifier = "MIT"
