# SPDX-License-Identifier: ICU
# Copyright (c) 2022-2023 The DPS8M Development Team
baseURL             = "http://dps8m.gitlab.io/dps8m"
title               = "DPS8M Simulator"
theme               = "hugo-geekdoc"
pluralizeListTitles = false
pygmentsUseClasses  = true
pygmentsCodeFences  = true
disablePathToLower  = true
enableGitInfo       = true
enableRobotsTXT     = false

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel   = 9

[taxonomies]
  tag = "tags"

[params]
  geekdocAlign            = "left"
  geekdocAnchor           = true
  geekdocBackToTop        = false
  geekdocBreadcrumb       = false
  geekdocDarkModeCode     = false
  geekdocImageLazyLoading = true
  geekdocLogo             = "multics-rings.png"
  geekdocMenuBundle       = true
  geekdocNextPrev         = false
  geekdocRepo             = "gitlab.com/dps8m/dps8m"
  geekdocSearch           = false
  geekdocToC              = false

[minify]
  disableHTML = true
