#!/usr/bin/env bash
grep --line-buffered \
-ve 'rm -Rf .*' \
-ve 'git clone .*' \
-ve 'git checkout .*' \
-ve '^Cloning into .*' \
-ve '^Already on .*' \
-ve '^Your branch is up to date with .*' \
-ve 'git status' \
-ve '^On branch .*' \
-ve 'nothing to commit, working tree clean' \
-ve 'cd .*dps8.*clean.all$' \
-ve 'ake.*ntering directory.*' \
-ve 'ake.*eaving directory.*' \
-ve '^CLEAN: .*' \
-ve 'AM ..T' \
-ve 'PM ..T' \
-ve 'AM UTC' \
-ve 'PM UTC' \
-ve 'make clean' \
-ve 'mkdir .*' \
-ve 'WARNING: Git re-build: .*' \
-ve ' or build from top-level' \
-ve 'cp \..*' \
-ve '^DPS8/M .imulator.*' \
-ve '^L68 .imulator.*' \
-ve 'Options: .*' \
-ve 'Commit: .*' \
-ve '^PVID .*' \
-ve '^LVID .*' \
-ve '^Registered .*/.*/.*' \
-ve 'volume_registration_mgr_.check_volume_registration: Reregistered.*ID.*' \
-ve '^r ..:.. .* .*$' \
-ve 'Loading FNP ., .*' \
-ve 'FNP . loaded successfully' \
-ve 'lg_ctl_: login word is .*' \
-ve ' .. messages copied into:.*' \
-ve ' ....... messages processed,' \
-ve 'syserr seq_num .*\.' \
-ve ' ....  bk ' \
-ve ' ....  ut.*copy_dump: Attempt to re-copy an invalid dump.' \
-ve '--> bk' \
-ve ' do -absentee' \
-ve ' ....  ...*Created .*...message' \
-ve ' ....  .. .* pb .*root' \
-ve ' Process . in .*Salvager.' \
-ve ' Segment quota used changed from .* to .*' \
-ve ' LOGOUT.*\..*:.*' \
-ve '^cycles = [0-9].*' \
-ve '^instructions.*[0-9].*' \
-ve '^lockCnt.*[0-9].*' \
-ve '^lockImmediate.*[0-9].*' \
-ve '^lockWait.*[0-9].*' \
-ve '^lockYield.*[0-9].*' \
-ve ' ....  vinc ' \
-ve ' ....  .. .*rpv.*pb.*root' \
-ve 'Cutoff date:.*/.*' \
-ve 'Automatic update: users = .*' \
-ve '^core_read2:.*locked.*locked_addr.*' \
-ve ' LOGIN.*\..*' \
-ve ' ut   completed.$' \
-ve ' send_admin_command: Execution started ...' \
-ve ' sc_admin_command_:.*delete_old_pdds' \
-ve ' sc_admin_command_:.*Completed command.' \
-ve 'FNP telnet server port set to ....' \
-ve '^Ready$' \
-ve 'auto-input.* login IO SysDaemon pun.' \
-ve 'auto-input.* x auto on' \
-ve ' Enter command:.*coordinator, driver, or logout:' \
-ve '-->  prt.' \
-ve '--> ut' \
-ve 'Sun pst$' \
-ve 'Mon pst$' \
-ve 'Tue pst$' \
-ve 'Wed pst$' \
-ve 'Thu pst$' \
-ve 'Fri pst$' \
-ve 'Sat pst$' \
-ve '--> cord' \
-ve '--> pun.' \
-ve 'Some deletions may not be performed.' \
-ve ' cord ... Coordinator initialized' \
-ve ' Coordinator Version: .' \
-ve ' rd.. Card input started.' \
-ve 'RCP: Detached .... from .*\..*' \
-ve 'RCP: Errors .rd.....' \
-ve 'RCP: Attached tapa_ for Utility' \
-ve 'RCP: Detached tapa_ from Clayton.SysAdmin' \
-ve 'as LOGOUT Clayton.SysAdmin.a' \
-ve 'sending escape' \
-ve 'MIPS AVE.*NANOSECONDS' \
-ve 'Summary from.*pst.*to' \
-ve 'Disk usage for.*pst.*to' \
-ve 'Syserr log from.*pst.*to' \
-ve '^\. pst Sun' \
-ve '^\. pst Mon' \
-ve '^\. pst Tue' \
-ve '^\. pst Wed' \
-ve '^\. pst Thu' \
-ve '^\. pst Fri' \
-ve '^\. pst Sat' \
-ve '\ UTC$' \
-ve '^d\.h$' \
-ve ' connect to address.*:.*Connection refused' \
-ve '^HSLA Port .*' \
-ve '^Map attached to file .*backup.map' \
-ve '^MR.* up at .* after shutdown at .*' \
-ve 'set_flagbox auto_reboot true' \
-ve 'auto-input.* x io1' \
-ve 'sc_command r cord coordinator$' \
-ve 'pause ..' \
-ve 'CONSOLE: ALERT' \
-ve 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$' \
-ve 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$' \
-ve 'Listen error address already in use' \
-ve 'Clayton.SysAdmin.*tc_data, .*pdd.*' \
-ve 'DESTROY.*looc.*' \
-ve 'SysDaemon.*Level.*directory.*system_library.*switch turned off.*' \
-ve '\*\*\*\*\*\*\*\*\*' \
-ve '....pun.$' \
-ve 'd\.h000.' \
-ve 'd\.h031.' \
/dev/stdin
