#!/bin/tcsh
echo "Downloading tape files..."
mkdir -p tapes
cd tapes
rm *.tap
wget https://s3.amazonaws.com/eswenson-multics/public/releases/MR12.7/12.7MULTICS.tap
wget https://s3.amazonaws.com/eswenson-multics/public/releases/MR12.7/12.7EXEC.tap
wget https://s3.amazonaws.com/eswenson-multics/public/releases/MR12.7/12.7LDD_STANDARD.tap
wget https://s3.amazonaws.com/eswenson-multics/public/releases/MR12.7/12.7UNBUNDLED.tap
wget https://s3.amazonaws.com/eswenson-multics/public/releases/MR12.7/12.7MISC.tap
wget https://s3.amazonaws.com/eswenson-multics/public/releases/MR12.7/12.7LISTINGS.tap
gunzip <foo.tap.gz >foo.tap
cd ..
