# DPS/8M documentation: docs/GNUmakefile
# vim: filetype=make:tabstop=4:tw=78
#
##############################################################################
#
# Copyright (c) 2022 The DPS8M Development Team
#
# All rights reserved.
#
# This software is made available under the terms of the ICU
# License, version 1.8.1 or later.  For more details, see the
# LICENSE.md file at the top-level directory of this distribution.
#
##############################################################################

.PHONY: all
all:
	@./builddoc.sh

##############################################################################
