# DPS8M simulator: src/Makefile.doc
# vim: filetype=make:tabstop=4:ai:cc=79:noexpandtab:list:listchars=tab\:\>\-
# SPDX-License-Identifier: MIT-0
# scspell-id: 0c00aace-f62b-11ec-ac9b-80ee73e9b8e7
# Copyright (c) 2022-2024 The DPS8M Development Team

###############################################################################

.NOTPARALLEL:

###############################################################################
# DPS8M Omnibus Documentation Targets
    # XXXX:    # ----------------------- Documentation ----------------------
###############################################################################

###############################################################################
# Book-style PDF

.PHONY: docspdf
ifneq (,$(findstring docs,$(MAKECMDGOALS)))
.NOTPARALLEL: docspdf
endif
docspdf:                                                                      \
    # docspdf:    # Build Omnibus Docs (Book-style PDF)
	@( cd "docs" && $(ENV) sh "./shell/builddoc.sh" )

###############################################################################
# Print-only PDF

.PHONY: docsprt
ifneq (,$(findstring docs,$(MAKECMDGOALS)))
.NOTPARALLEL: docsprt
endif
docsprt:                                                                      \
    # docsprt:    # Build Omnibus Docs (Print-only PDF)
	@( cd "docs" && $(ENV) ONESIDE=1 sh "./shell/builddoc.sh" )

###############################################################################
# Docker Book-style PDF

.PHONY: dokdocspdf
ifneq (,$(findstring docs,$(MAKECMDGOALS)))
.NOTPARALLEL: dokdocspdf
endif
dokdocspdf:                                                                   \
    # dokdocspdf:    # Build Omnibus Docs (Docker, Book)
	@( cd "docs" && $(ENV) sh "./shell/builddoc-docker.sh" )

###############################################################################
# Docker Print-only PDF

.PHONY: dokdocsprt
ifneq (,$(findstring docs,$(MAKECMDGOALS)))
.NOTPARALLEL: dokdocsprt
endif
dokdocsprt:                                                                   \
    # dokdocsprt:    # Build Omnibus Docs (Docker, Print)
	@( cd "docs" && $(ENV) ONESIDE=1 sh "./shell/builddoc-docker.sh" )

###############################################################################

# Local Variables:
# mode: make
# tab-width: 4
# End:
