# DPS8M simulator: src/Makefile.doc
# vim: filetype=make:tabstop=4:tw=79:noexpandtab
# SPDX-License-Identifier: ICU
# scspell-id: 0c00aace-f62b-11ec-ac9b-80ee73e9b8e7

###############################################################################
#
# Copyright (c) 2022 The DPS8M Development Team
#
# All rights reserved.
#
# This software is made available under the terms of the ICU
# License, version 1.8.1 or later.  For more details, see the
# LICENSE.md file at the top-level directory of this distribution.
#
###############################################################################

###############################################################################
# DPS8M Omnibus Documentation Targets
    # XXXX:    # ----------------------- Documentation ----------------------
###############################################################################

###############################################################################
# Book-style PDF

.PHONY: docspdf
ifneq (,$(findstring docs,$(MAKECMDGOALS)))
.NOTPARALLEL: docspdf
endif
docspdf:                                                                      \
    # docspdf:    # Build Omnibus Docs (Book-style PDF)
	@($(MAKE))
	@( cd "docs" && $(ENV) sh "./builddoc.sh" )

###############################################################################
# Print-only PDF

.PHONY: docsprt
ifneq (,$(findstring docs,$(MAKECMDGOALS)))
.NOTPARALLEL: docsprt
endif
docsprt:                                                                      \
    # docsprt:    # Build Omnibus Docs (Print-only PDF)
	@($(MAKE))
	@( cd "docs" && $(ENV) ONESIDE=1 sh "./builddoc.sh" )

###############################################################################

# Local Variables:
# mode: make
# tab-width: 4
# End:
