# DPS/8M simulator: src/Makefile.dep
# vim: filetype=make:tabstop=4:tw=76
#
###############################################################################
#
# Copyright (c) 2021 The DPS8M Development Team
#
# All rights reserved.
#
# This software is made available under the terms of the ICU
# License, version 1.8.1 or later.  For more details, see the
# LICENSE.md file at the top-level directory of this distribution.
#
###############################################################################

###############################################################################
# Dependency Management Targets                                               \
    # XXXX:    # ------------------- Dependency Management ------------------
###############################################################################

###############################################################################
# Downloads and verifies dependencies

.PHONY: get-libuv
.NOTPARALLEL: get-libuv
get-libuv:                                                                    \
    # get-libuv:    # Download, verify, and extract libuv
	@$(SETV); $(TRUE)

###############################################################################

.PHONY: get-libpopt
.NOTPARALLEL: get-libpopt
get-libpopt:                                                                  \
    # get-libpopt:    # Download, verify, and extract libpopt
	@$(SETV); $(TRUE)

###############################################################################

# Local Variables:
# mode: make
# tab-width: 4
# End:
