# DPS/8M simulator: src/Makefile.scc
# vim: filetype=make:tabstop=4:tw=76
#
###############################################################################
#
# Copyright (c) 2021 Jeffrey H. Johnson <trnsz@pobox.com>
# Copyright (c) 2021 The DPS8M Development Team
#
# All rights reserved.
#
# This software is made available under the terms of the ICU
# License, version 1.8.1 or later.  For more details, see the
# LICENSE.md file at the top-level directory of this distribution.
#
###############################################################################

###############################################################################
# Development Tools Targets                                                 \
    # XXXX:    # --------------------- Development Tools --------------------
###############################################################################

###############################################################################
# Displays preprocessor definitions

.PHONY: printdefs
printdefs:                                                                    \
    # printdefs:    # Display selected preprocessor defines
	@( ( $(MAKE) "$$($(GIT) rev-parse --show-toplevel)/./src/unifdef/unifdef" \
     2> /dev/null; $(FIND) . -name '*.[ch]' -exec $(SH) -c "export n2=\"{}\"; \
      $(PRINTF) '%s ' \"\$${n2:?}\";                                          \
       "$$($(GIT) rev-parse --show-toplevel)/./src/unifdef/unifdef" "-Stn"    \
        \"\$${n2:?}\"" \; | while read -r n; do $(PRINTF) '%s  %s \n'         \
         $$($(PRINTF) '%s ' "$${n:?}" | $(WC) -w) "$${n:?}"; done           | \
          $(SORT) -urn | $(EXPAND) | $(CUT) -d ' ' -f 2-                    | \
           $(SED) -e 's/ S.._.*H_ / /g' -e 's/ DEC.* / /g' | $(TR) -s ' '   | \
            $(SED) -e 's/^\ //g' | $(SED) -e 's/^\.\/.*\.[ch] \./\./g'        \
             -e 's/^\.\/.*[ch] $$//g' | $(GREP) -v '^$$') ) | while read      \
              line; do $(PRINTF) '%s\n' "$${line:?} "                       | \
               $(AWK) '{ for (i=1; i<=NF; i++) if (!a[$$i]++)                 \
                printf("%s%s", $$i, FS); } { printf("\n"); }'; done         | \
                 $(SED) 's/ /: /'

###############################################################################
# Convenience target: Runs Cppcheck

.PHONY: cppcheck
cppcheck:                                                                    \
    # cppcheck:    # Start Cppcheck linter and save output
	-@$(RMF) ./cppcheck.txt > /dev/null 2>&1 || $(TRUE)
	@( $(PRINTF) '%s\n' "Starting in 5s, saving output to cppcheck.txt";     \
      $(SLEEP) 5 && ./src/ci-kit/cppcheck.sh 2> "cppcheck.txt" || $(TRUE) )

###############################################################################
# Convenience target: Runs Oracle Developer Studio 12.6 Lint

.PHONY: orstlint
orstlint:                                                                    \
    # orstlint:    # Start Oracle Studio Lint & save output
	-@$(RMF) ./orstlint.txt > /dev/null 2>&1 || $(TRUE)
	@( $(PRINTF) '%s\n' "Starting now, saving output to orstlint.txt";       \
      export CSTD="gnu11" && export CFLAGS="-DNO_C_ELLIPSIS" && cd src/dps8  \
       && $(MAKE) -i -k -s dps8 CC="$(ORSTLINT) -u -xO5 -m64 -xCC -a         \
        -errshort=full -err=warn -errfmt=src -errtags=yes -m -v -x           \
         -features=gcc_enums                                                 \
          -erroff=E_STATIC_UNUSED,E_CONSTANT_CONDITION,E_SEC_STRNCPY_WARN"   \
          SUNPRO=1 SUNLINT=1 NEED_128=1 --output-sync ) 2>&1 |               \
          $(GREP) -v -E '(^make: .* Error 2$$|no output created$$|make: .* not remade because of errors.$$|^lint.*annot find source file.*\.o$$|^lint:.*o input source files specified.*no output generated$$)' | $(TEE) orstlint.txt;       \
           $(CAT) orstlint.txt | $(GREP) '^E_' | $(CUT) -d ',' -f 1 |        \
            $(SORT) | $(UNIQ) -c | $(SORT) -rn | $(TEE) -a orstlint.txt

###############################################################################

# Local Variables:
# mode: make
# tab-width: 4
# End:
